# Generated by Django 5.0.1 on 2024-01-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='ProductInventory',
        ),
    ]
