# Generated by Django 5.0.1 on 2024-01-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_title_productinventory_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='description',
        ),
    ]
