# Generated by Django 5.0.1 on 2024-01-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_bag_datecreated_remove_bag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date_started',
        ),
        migrations.AddField(
            model_name='group',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
