# Generated by Django 5.0.1 on 2024-02-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_group_date_started_group_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='name',
            new_name='brandname',
        ),
    ]
